#!/bin/sh

# originally from https://github.com/n3llyb0y/docker-wait
# (b037dc35fbeb8ab418fbed516c0930ea4990fb54), modified to exec for use
# as an entrypoint.

set -e

DEFAULT_TIMEOUT=30

ports=$PORTS

# set the per host:port connection timeout
if [ -n "$TIMEOUT" ]; then
  timeout=$TIMEOUT
else
  timeout=$DEFAULT_TIMEOUT
fi

addrs="$(env | grep '_PORT=' | egrep -v 'TCP|UDP' | cut -d = -f 2 | sort -u)"

# empty ports variable will default to checking for exactly one port
if [ -z "$ports" ]; then
    echo 'no linked ports to wait for'
    exec "$@"
fi

for a in $addrs; do
    a="$(echo $a | cut -d / -f 3)"
    host="$(echo $a | cut -d : -f 1)"
    port="$(echo $a | cut -d : -f 2)"

    seconds=0
    while [ "$seconds" -lt "$timeout" ] && ! nc -z -w1 $host $port; do
        echo -n .
        seconds=$((seconds+1))
        sleep 1
    done

    if [ "$seconds" -lt "$timeout" ]; then
        echo "$host:$port up!"
    else
        echo "$host:$port WARN: unable to connect"
    fi
done

echo "all ready"

exec "$@"
